#!/bin/sh
#
# makesrcdist - make a source distribution of PAPPL.
#

if test $1 = "--snapshot"; then
    snapshot=1
    shift
else
    snapshot=0
fi

if test $# != 1; then
    echo "Usage: ./makesrcdist [--snapshot] VERSION"
    exit 1
fi

version=$1

# Check that version number has been updated everywhere...
if test $(grep AC_INIT configure.ac | awk '{print $2}') != "[$version],"; then
    echo "Still need to update AC_INIT version in 'configure.ac'."
    exit 1
fi

if test $(grep PAPPL_VERSION= configure | awk -F \" '{print $2}') != "$version"; then
    echo "Still need to run 'autoconf -f'."
    exit 1
fi

if test $(grep '<version>' vcnet/libpappl1_native.nuspec | sed -E -e '1,$s/^.*<version>([0-9]+\.[0-9]+\.[0-9]+).*$/\1/') != "$version"; then
    echo "Still need to update version in 'vcnet/libpappl1_native.nuspec'."
    exit 1
fi

if test $(grep '<version>' vcnet/libpappl1_native.redist.nuspec | sed -E -e '1,$s/^.*<version>([0-9]+\.[0-9]+\.[0-9]+).*$/\1/') != "$version"; then
    echo "Still need to update version in 'vcnet/libpappl1_native.redist.nuspec'."
    exit 1
fi

if test $(grep PAPPL_VERSION vcnet/config.h | awk -F \" '{print $2}') != "$version"; then
    echo "Still need to update PAPPL_VERSION in 'vcnet/config.h'."
    exit 1
fi

if test $(grep PAPPL_VERSION xcode/config.h | awk -F \" '{print $2}') != "$version"; then
    echo "Still need to update PAPPL_VERSION in 'xcode/config.h'."
    exit 1
fi

if test $(grep "Version:" pappl.spec | awk '{print $2}') != "$version"; then
    echo "Still need to update Version in 'pappl.spec'."
    exit 1
fi


# Tag as needed...
if test $snapshot = 0; then
    echo Creating tag for release...
#    git tag -m "Tag $version" v$version
#    git push origin v$version
fi

exit 0

# Make source archives...
echo Creating pappl-$version.tar.gz...
git archive --format tar --prefix=pappl-$version/ HEAD | gzip -v9 >pappl-$version.tar.gz
gpg --detach-sign pappl-$version.tar.gz

echo Creating pappl-$version.zip...
git archive --format zip --prefix=pappl-$version/ HEAD >pappl-$version.zip
gpg --detach-sign pappl-$version.zip
