#!/bin/sh
#
# makesrcdist - make a source distribution of PAPPL.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating pappl-$version.tar.gz...
git archive --format tar --prefix=pappl-$version/ HEAD | gzip -v9 >pappl-$version.tar.gz
gpg --detach-sign pappl-$version.tar.gz

echo Creating pappl-$version.zip...
git archive --format zip --prefix=pappl-$version/ HEAD >pappl-$version.zip
gpg --detach-sign pappl-$version.zip
